"""add door map fields

Revision ID: 6cf3866caeb2
Revises: c2bba54217ab
Create Date: 2026-02-13 15:20:36.987677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf3866caeb2'
down_revision: Union[str, None] = 'c2bba54217ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doors', sa.Column('site', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doors', 'site')
    # ### end Alembic commands ###
