"""add door map fields

Revision ID: b41777e28d74
Revises: b1847f924916
Create Date: 2026-02-12 18:26:39.943712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41777e28d74'
down_revision: Union[str, None] = 'b1847f924916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doors', sa.Column('site', sa.String(length=80), nullable=False))
    op.add_column('doors', sa.Column('x', sa.Float(), nullable=False))
    op.add_column('doors', sa.Column('y', sa.Float(), nullable=False))
    op.create_index(op.f('ix_doors_site'), 'doors', ['site'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doors_site'), table_name='doors')
    op.drop_column('doors', 'y')
    op.drop_column('doors', 'x')
    op.drop_column('doors', 'site')
    # ### end Alembic commands ###
