"""add door coords

Revision ID: c2bba54217ab
Revises: b41777e28d74
Create Date: 2026-02-12 23:32:39.980735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2bba54217ab'
down_revision: Union[str, None] = 'b41777e28d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doors_site', table_name='doors')
    op.drop_column('doors', 'site')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doors', sa.Column('site', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_index('ix_doors_site', 'doors', ['site'], unique=False)
    # ### end Alembic commands ###
